language: ruby

before_install:
  - gem install bundler

cache: bundler

matrix:
  include:
    - rvm: 1.9.3
      env: PUPPET_VERSION=3.7
    - rvm: 1.9.3
      env: PUPPET_VERSION=3.8
    - rvm: 2.2.0
      env: PUPPET_VERSION=4.0
    - rvm: 2.2.0
      env: PUPPET_VERSION=4.1
    - rvm: 2.2.0
      env: PUPPET_VERSION=4.2
    - rvm: 2.2.0
      env: PUPPET_VERSION=4.3
    - rvm: 2.2.0
      env: PUPPET_VERSION=4.4
    - rvm: 2.2.0
      env: PUPPET_VERSION=4.5

before_deploy:
  - rvm 1.9.3 do gem install mime-types -v 2.6.2
  - rvm 1.9.3 do gem install rest-client -v 1.8.0
deploy:
  provider: puppetforge
  user: swisscom
  password:
    secure: "RW9hoPcdRCxSSCcKYLtmz4RUy4UwmmS1mmDT/lmHNqdMBizoR+/9ealy0vGEhGvMpzoACETHVgyMUp/E7oDCFIT5XV77/3ibdjU/RL1voFgbkdf7GAAp8BWXbtiUjj6e21WdRCN+T1xkAWrOPV+RhFn0kFpDcFEpZ8VhalhcgCmBHhoa9LFuyusa8OazVkWFUfWzsZb134+kNp6bd3MVsuVongjvUnIQUrV3q/1E1/43g/otrI9qLkiTlZgEAEoxMtDzFk7qLfRWHK5jOu2AeSItIjXuUjQ9zEg7bXkrFejAANX/FYRqPPpdMeUqEeAFM+MdjXV/KADWjcmQHexwc2RWNwnOPC88OTkZJGCkzbJXylqPGcnade7CjyO/Yubs4NRxv52tuFU+GdoMDVTe1wCNkfcV42nnxL3uBeqv5phWo2YgXBZfbKKXXokiTSyaxIavpKtQJSVJN5v68ZnhUsCCkFJJ6FYsiurfrOJCSbRBPVptEZADbLL62WRYQs3j4V1bCIgGntXZ4Xg2oz+YKIJ0cjMgb0SHpNU22qnLuP369Z1ZVVtuGhc2sAz9BMfRVw4BGp0v/r3v92HwNwzu9P3RXOjcaAkqQPuRYJFPl+7K3HwviRnY8uUZncHbrrRFmWjqhYXqB/DDkMGKMAJ2mmGj/OIALmhEBD1/fUGbO2s="
  on:
    tags: true
    branch: 'master'
    # only deploy once
    rvm: 2.2.0
    env: PUPPET_VERSION=4.5
